import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from 'next/image';

const Footer = () => {
  return (
    <footer style={{ padding: '20px', backgroundColor: '#3b3b3b', color: '#fff' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontFamily: 'GeistMonoVF', maxWidth: '1200px', margin: '0 auto' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <Image
            src="/icons/motionlogo.png" // Replace with your icon path
            width={60} // Reduced width for cleaner layout
            height={60} // Reduced height for cleaner layout
            alt="Icon"
          />
          <span style={{ fontSize: '0.9rem' }}>
            &copy; {new Date().getFullYear()} Made by Raj Kalakheti
          </span>
        </div>
        <p style={{ maxWidth: '500px', textAlign: 'right', fontSize: '0.85rem', margin: 0, lineHeight: '1.4' }}>
          Built with Next.js, serverless API routes, Tailwind CSS, Framer Motion, and OpenAI API, and deployed on Vercel.
        </p>
      </div>
    </footer>
  );
};
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}